### ISSUE TITLE
why is this universe not updating?

### ISSUE THREAD

**Issue by drmowinckels** [r-universe/lifebrain#1]
I recently added a [universe repo](https://github.com/Lifebrain/universe) for this org, with a [package.json](https://github.com/Lifebrain/universe/blob/main/package.json), but its not triggering any updates.
Did I miss part of the setup?

**Comment by drmowinckels** [comment]
@jeroen tagging for help.

**Comment by jeroen** [comment]
I think there is a syntax error in your package.json at the end: https://github.com/Lifebrain/universe/blob/main/package.json

**Comment by drmowinckels** [comment]
Hi yeah, sorry, I introduced that just an hour ago. Before that though, it looked ok. For instance, I made the repo and package.json first time 22nd of June, and the syntax looked ok then? But the universe still only has the single package in it, and the actions arent being triggered.

https://github.com/Lifebrain/universe/commit/755044def98c0e1f9e261bcdbee0354b18f513f5

**Comment by jeroen** [comment]
OK I'll have a look, thanks!

**Comment by jeroen** [comment]
The file has to be called `packages.json` (plural) instead of `package.json`

**Comment by drmowinckels** [comment]
its always something small but obvious :) 
Thank you!
